openapi: 3.0.0
info:
  title: ONDC Specification
  description: ONDC Specification
  version: 2.0.0
security:
  - SubscriberAuth: []
paths:
  /search:
    post:
      tags:
        - Provider Platform
        - Gateway
      description: Consumer Platform declares the customer's intent to buy/avail products
        or services
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Search.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /select:
    post:
      tags:
        - Provider Platform
      description: Consumer Platform declares the customer's cart (or equivalent) created
        by selecting objects from the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Select.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /init:
    post:
      tags:
        - Provider Platform
      description: Initialize an order by providing billing and/or shipping details
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Init.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /confirm:
    post:
      tags:
        - Provider Platform
      description: Initialize an order by providing billing and/or shipping details
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Confirm.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /status:
    post:
      tags:
        - Provider Platform
      description: Fetch the latest order object
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Status.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  # /track:
  #   post:
  #     tags:
  #       - Provider Platform
  #     description: Track an active order
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: ../../beckn-core/api/transaction/components/io/Track.yaml
  #     responses:
  #       default:
  #         $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /cancel:
    post:
      tags:
        - Provider Platform
      description: Cancel an order
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Cancel.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /update:
    post:
      tags:
        - Provider Platform
      description: Remove object
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Update.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /rating:
    post:
      tags:
        - Provider Platform
      description: Provide feedback on a service
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Rating.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /support:
    post:
      tags:
        - Provider Platform
      description: Contact support
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/Support.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_search:
    post:
      tags:
        - Consumer Platform
      description: Provider Platform sends its catalog in response to a search request.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnSearch.yaml
            
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_select:
    post:
      tags:
        - Consumer Platform
      description: Send draft order object with quoted price for selected items
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnSelect.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_init:
    post:
      tags:
        - Consumer Platform
      description: Send order object with payment details updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnInit.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_confirm:
    post:
      tags:
        - Consumer Platform
      description: Send active order object
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnConfirm.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  # /on_track:
  #   post:
  #     tags:
  #       - Consumer Platform
  #     description: Send tracking details of an active order
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: ../../beckn-core/api/transaction/components/io/OnTrack.yaml
  #     responses:
  #       default:
  #         $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_cancel:
    post:
      tags:
        - Consumer Platform
      description: Send cancellation request_id with reasons list in case of cancellation
        request. Else send cancelled order object
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnCancel.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_update:
    post:
      tags:
        - Consumer Platform
      description: Returns updated service with updated runtime object
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnUpdate.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_status:
    post:
      tags:
        - Consumer Platform
      description: Fetch the status of a Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnStatus.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_rating:
    post:
      tags:
        - Consumer Platform
      description: Provide feedback on a service
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnRating.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
  /on_support:
    post:
      tags:
        - Consumer Platform
      description: Contact Support
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../beckn-core/api/transaction/components/io/OnSupport.yaml
      responses:
        default:
          $ref: ../../beckn-core/api/transaction/components/io/Response.yaml
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >-
        Signature of message body using Consumer Platform or Provider Platform
        subscriber's signing public key.
        <br/><br/>Format:<br/><br/><code>Authorization : Signature
        keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created)
        (expires) digest",signature="Base64(signing string)"</code>
  schemas:
    $ref: ../../beckn-core/api/transaction/components/schema/index.yaml